remote_theme: just-the-docs/just-the-docs
title: Actions URI
description: A plugin for Obsidian.md adding additional `x-callback-url` endpoints to the app for common actions — it's a clean, super-charged addition to Obsidian URI.

baseurl: "/obsidian-actions-uri"
url: "https://czottmann.github.io"

permalink: pretty

aux_links:
  "Actions URI on GitHub":
    - "https://github.com/czottmann/obsidian-actions-uri"

# External navigation links
nav_external_links:
  - title: "Actions URI on GitHub"
    url: "https://github.com/czottmann/obsidian-actions-uri"
  - title: "Actions URI in Community Plugins"
    url: "https://obsidian.md/plugins?id=actions-uri"

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "tests" collection
    routes:
      # Give the collection a name
      name: Routes
      nav_fold: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Copyright &copy; 2022 <a href="https://github.com/czottmann">Carlo Zottmann</a>. <a href="https://github.com/czottmann/obsidian-actions-uri/tree/main/LICENSE.txt">MIT licensed.</a>'
